FROM python:3.9.14-slim-buster
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY . /app
RUN chmod +x /app/bootstrap-docker-app.sh
RUN /app/bootstrap-docker-app.sh
RUN chmod +x /app/startup-app.sh
CMD ["sh","/app/startup-app.sh"]