# Generated by Django 4.1.2 on 2022-10-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sockets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('power_on', models.BooleanField(default=False)),
                ('switch_lock', models.BooleanField(default=False)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
            ],
            options={
                'verbose_name_plural': 'Sockets',
            },
        ),
    ]
